<!--
/**
 * Plopocom_Insta extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Plopocom
 * @package        Plopocom_Insta
 * @copyright      Copyright (c) 2019
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
-->
<a href="<?php echo Mage::registry('current_post')->getLink() ?>" target="_blank">
    <img src="<?php echo Mage::registry('current_post')->getMediaUrl() ?>" alt="<?php echo Mage::registry('current_post')->getAlt() ?>" style="max-width: 200px;">
</a>
